name: Restart Hugging Face Space Container

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 00:00 执行
  workflow_dispatch:  # 允许手动触发测试

jobs:
  restart-hf-uu-pixiv-api:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/uu_pixiv_api/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
