name: Restart Hugging Face Space Container

on:
  schedule:
    - cron: '0 */3 * * *'  # 每 3 小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  restart-hf-uu-pixiv-api:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/uu_pixiv_api/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
  restart-hf-pixiv:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/pixiv/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
  restart-hf-payHook:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/payHook/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
  restart-hf-iizhiApi:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/iizhiApi/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
  restart-hf-static_config:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/static_config/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
  restart-hf-v2b_proxy:
    runs-on: ubuntu-latest
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  # 存储你的 Hugging Face Space API Token
        run: |
          curl -X POST "https://huggingface.co/api/spaces/rogerxavier/v2b_proxy/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
