name: Restart Hugging Face Space Containers

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨 00:00 执行
    - cron: '0 1 * * *'  # 每天凌晨 01:00 执行
    - cron: '0 2 * * *'  # 每天凌晨 02:00 执行
    - cron: '0 3 * * *'  # 每天凌晨 03:00 执行
    - cron: '0 4 * * *'  # 每天凌晨 04:00 执行
    - cron: '0 5 * * *'  # 每天凌晨 05:00 执行
  workflow_dispatch:  # 允许手动触发

jobs:
  restart-hf-uu-pixiv-api:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * *'  # 每天凌晨 00:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/uu_pixiv_api/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"

  restart-hf-pixiv:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 1 * * *'  # 每天凌晨 01:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/pixiv/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"

  restart-hf-payHook:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 2 * * *'  # 每天凌晨 02:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/payHook/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"

  restart-hf-iizhiApi:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 3 * * *'  # 每天凌晨 03:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/iizhiApi/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"

  restart-hf-static_config:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 4 * * *'  # 每天凌晨 04:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/static_config/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"

  restart-hf-v2b_proxy:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 5 * * *'  # 每天凌晨 05:00
    steps:
      - name: Restart Hugging Face Space Container
        env:
          HF_SPACE_API_TOKEN: ${{ secrets.HF_SPACE_API_TOKEN }}  
        run: |
          curl -X POST "https://huggingface.co/api/spaces/v2b_proxy/restart" \
          -H "Authorization: Bearer $HF_SPACE_API_TOKEN"
