name: Check and Restart Hugging Face Space

on:
  workflow_dispatch:  # 允许手动触发
  
jobs:
  check-space-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Space Status
        id: check_status
        run: |
          SPACE_NAME="rogerxavier/uu_pixiv_api"
          TOKEN="${{ secrets.HUGGING_FACE_TOKEN }}"
          
          response=$(curl -s -H "Authorization: Bearer $TOKEN" "https://huggingface.co/api/spaces/$SPACE_NAME")
          
          stage=$(echo "$response" | jq -r '.runtime.stage')

          echo "Space stage: $stage"
          echo "::set-output name=stage::$stage"
      - name: Check Space Status and restart
        if: steps.check_status.outputs.stage != 'RUNNING'
        run: |
          SPACE_NAME="rogerxavier/uu_pixiv_api"
          TOKEN="${{ secrets.HUGGING_FACE_TOKEN }}"
    
          echo "Restarting the space..."
          curl -X POST -H "Authorization: Bearer $TOKEN" "https://huggingface.co/api/spaces/$SPACE_NAME/restart"

       
          
